on:
    push:
        branches: [develop, main]
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: checkout
            - name: PolFrantz
              run: ./MonScript.sh
